# Generated by Django 3.0.6 on 2020-05-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateHW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default='30/05/2020')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('about', models.TextField(max_length=512, unique=True)),
                ('image', models.FileField(upload_to='upload/img')),
                ('file', models.FileField(upload_to='upload/HW')),
                ('source', models.URLField(null=True)),
            ],
        ),
    ]
