# Generated by Django 3.0.6 on 2020-06-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='affiliation',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='affiliation',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='textbooks',
            old_name='affiliation',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='affiliation',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='audio',
            name='published',
            field=models.DateTimeField(default='2020-06-09 08:24'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='image',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='homework',
            name='published',
            field=models.DateTimeField(default='2020-06-09 08:24'),
        ),
        migrations.AlterField(
            model_name='source',
            name='published',
            field=models.DateTimeField(default='2020-06-09 08:24'),
        ),
        migrations.AlterField(
            model_name='textbooks',
            name='published',
            field=models.DateTimeField(default='2020-06-09 08:24'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, upload_to='upload/video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.FileField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='video',
            name='published',
            field=models.DateTimeField(default='2020-06-09 08:24'),
        ),
    ]
