# Generated by Django 3.0.6 on 2020-05-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createhw',
            name='published',
            field=models.DateTimeField(default='30-05-2020'),
        ),
    ]
