# Generated by Django 3.0.6 on 2020-06-08 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('educational_materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='date_joined',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_materials.Groups'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='invite_reason',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='published',
            field=models.DateTimeField(default='2020-06-09 00:28'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='published',
            field=models.DateTimeField(default='2020-06-09 00:28'),
        ),
        migrations.AlterField(
            model_name='source',
            name='published',
            field=models.DateTimeField(default='2020-06-09 00:28'),
        ),
        migrations.AlterField(
            model_name='textbooks',
            name='published',
            field=models.DateTimeField(default='2020-06-09 00:28'),
        ),
        migrations.AlterField(
            model_name='video',
            name='published',
            field=models.DateTimeField(default='2020-06-09 00:28'),
        ),
    ]
