# Generated by Django 3.0.6 on 2020-05-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_materials', '0003_auto_20200530_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createhw',
            name='published',
            field=models.DateTimeField(default='YYYY-MM-DD HH:MM'),
        ),
    ]
