# Generated by Django 3.0.6 on 2020-05-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_materials', '0004_auto_20200530_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default='2020-05-30 13:28')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('about', models.TextField(max_length=512, unique=True)),
                ('image', models.FileField(upload_to='upload/img')),
                ('file', models.FileField(upload_to='upload/FilesHW')),
                ('source', models.URLField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CreateHW',
        ),
    ]
