# Generated by Django 3.0.6 on 2020-05-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_materials', '0006_auto_20200530_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='about',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='homework',
            name='published',
            field=models.DateTimeField(default='2020-05-30 15:10'),
        ),
    ]
