# Generated by Django 3.0.6 on 2020-06-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_materials', '0007_auto_20200530_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='about',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='content',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='homework',
            name='published',
            field=models.DateTimeField(default='2020-06-04 11:12'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
