# Generated by Django 3.0.6 on 2020-06-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_materials', '0008_auto_20200604_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default='2020-06-05 00:13')),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=256)),
                ('file', models.FileField(upload_to='upload/audio')),
                ('source', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default='2020-06-05 00:13')),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=256)),
                ('image', models.FileField(upload_to='upload/url')),
                ('source', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Textbooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default='2020-06-05 00:13')),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=256)),
                ('image', models.FileField(upload_to='upload/textbooks')),
                ('file', models.FileField(upload_to='upload/textbooks')),
                ('source', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default='2020-06-05 00:13')),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=256)),
                ('image', models.FileField(upload_to='upload/video_img')),
                ('file', models.FileField(upload_to='upload/video')),
                ('source', models.URLField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='homework',
            name='published',
            field=models.DateTimeField(default='2020-06-05 00:13'),
        ),
    ]
