# Generated by Django 3.0.6 on 2020-06-04 21:29

from django.db import migrations, models
import educational_materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_materials', '0009_auto_20200605_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default='2020-06-05 00:29')),
                ('file', models.FileField(upload_to=educational_materials.models.user_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='audio',
            name='published',
            field=models.DateTimeField(default='2020-06-05 00:29'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='published',
            field=models.DateTimeField(default='2020-06-05 00:29'),
        ),
        migrations.AlterField(
            model_name='source',
            name='published',
            field=models.DateTimeField(default='2020-06-05 00:29'),
        ),
        migrations.AlterField(
            model_name='textbooks',
            name='published',
            field=models.DateTimeField(default='2020-06-05 00:29'),
        ),
        migrations.AlterField(
            model_name='video',
            name='published',
            field=models.DateTimeField(default='2020-06-05 00:29'),
        ),
    ]
